import { Topic } from './types';

export const EXAM_DATES = [
    "June 2013",
    "June 2014",
    "Dec 2015",
    "June 2017",
    "July 2018",
    "Dec 2018",
    "June 2019",
    "Dec 2019",
    "Oct 2020",
    "March 2021",
    "Nov 2021",
    "March 2022",
    "Sept 2022",
    "Feb 2023",
    "Aug 2023",
    "April 2024",
    "Aug 2024",
    "April 2025",
    "Oct 2025",
    "March 2026"
];

// Condensed dataset based on provided HTML. 
// Note: In a real scenario, we might fetch this from a JSON file, but keeping it here for the single-code-block requirement.
export const TOPICS: Topic[] = [
    { id: "1", sNo: 1, title: "Ulcerative, Vesicular and Bullous Lesions", link: "#", subject: "Oral Medicine", default10m: true, default2m: true, examDates: ["June 2013", "June 2017"] },
    { id: "2", sNo: 2, title: "Red and White Lesions", link: "#", subject: "Oral Medicine", examDates: ["June 2014", "Dec 2015"] },
    { id: "3", sNo: 3, title: "Pigmentation of the Oral Tissues", link: "#", subject: "Oral Medicine", examDates: ["July 2018"] },
    { id: "4", sNo: 4, title: "Benign Tumours of the Oral Cavity Including Gingival Enlargements", link: "#", subject: "Oral Medicine", examDates: ["Dec 2018"] },
    { id: "5", sNo: 5, title: "Oral Cancer", link: "#", subject: "Oral Medicine", examDates: ["June 2019"] },
    { id: "6", sNo: 6, title: "Diseases of the Tongue and Lips", link: "#", subject: "Oral Medicine" },
    { id: "7", sNo: 7, title: "Salivary Glands Diseases", link: "#", subject: "Oral Medicine" },
    { id: "8", sNo: 8, title: "Disorders of TMJ and MPDS", link: "#", subject: "Oral Medicine" },
    { id: "9", sNo: 9, title: "Ionizing Radiation and Regressive Alterations of the Oral Cavity", link: "#", subject: "Oral Medicine" },
    { id: "10", sNo: 10, title: "Odontologic Diseases", link: "#", subject: "Oral Medicine" },
    { id: "11", sNo: 11, title: "Orofacial Pain", link: "#", subject: "Oral Medicine" },
    { id: "12", sNo: 12, title: "Bacterial, Viral and Infectious Diseases of the Oral Cavity Including AIDS", link: "#", subject: "Oral Medicine" },
    { id: "13", sNo: 13, title: "Diseases of the Endocrine and Respiratory System: CVS and GIT", link: "#", subject: "Oral Medicine" },
    { id: "14", sNo: 14, title: "Metabolic Disorders", link: "#", subject: "Oral Medicine" },
    { id: "15", sNo: 15, title: "Haematologic Diseases", link: "#", subject: "Oral Medicine" },
    { id: "16", sNo: 16, title: "Diagnostic Laboratory Procedures", link: "#", subject: "Oral Medicine" },
    { id: "17", sNo: 17, title: "Miscellaneous", link: "#", subject: "Oral Medicine" },
    { id: "18", sNo: 18, title: "Radiation Physics", link: "#", subject: "Oral Radiology" },
    { id: "19", sNo: 19, title: "Radiation Biology, Hazards of Radiation and Radiation Protection", link: "#", subject: "Oral Radiology" },
    { id: "20", sNo: 20, title: "X-Ray Films and Accessories", link: "#", subject: "Oral Radiology" },
    { id: "21", sNo: 21, title: "Processing of X-Ray Films", link: "#", subject: "Oral Radiology" },
    { id: "22", sNo: 22, title: "Image Principles: X-Rays Quality Control", link: "#", subject: "Oral Radiology" },
    { id: "23", sNo: 23, title: "Intraoral Radiographic Techniques", link: "#", subject: "Oral Radiology" },
    { id: "24", sNo: 24, title: "Extraoral Radiographic Techniques", link: "#", subject: "Oral Radiology" },
    { id: "25", sNo: 25, title: "Specialized Imaging Techniques", link: "#", subject: "Oral Radiology" },
    { id: "26", sNo: 26, title: "Radiographic Interpretations", link: "#", subject: "Oral Radiology" },
    { id: "27", sNo: 27, title: "Introduction to Oral and Maxillofacial Surgery", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "28", sNo: 28, title: "General Principles of Surgery", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "29", sNo: 29, title: "Local Anaesthesia", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "30", sNo: 30, title: "Conscious Sedation and General Anaesthesia", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "31", sNo: 31, title: "Principles of Exodontia and Instrumentation", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "32", sNo: 32, title: "Impactions", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "33", sNo: 33, title: "Maxillofacial Trauma", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "34", sNo: 34, title: "Mandibular Fractures", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "35", sNo: 35, title: "Cysts of Orofacial Region", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "36", sNo: 36, title: "Benign Tumours of the Jaw", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "37", sNo: 37, title: "Diseases of TMJ", link: "#", subject: "Oral & Maxillofacial Surgery", default10m: true, default2m: true },
    { id: "38", sNo: 38, title: "Diseases of Salivary Gland", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "39", sNo: 39, title: "Diseases of Maxillary Sinus", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "40", sNo: 40, title: "Inflammatory Lesions of Jaw and Orofacial Infections", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "41", sNo: 41, title: "Facial Neuropathology", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "42", sNo: 42, title: "Preprosthetic Surgery", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "43", sNo: 43, title: "Premalignant and Malignant Lesions", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "44", sNo: 44, title: "Management of Medically Compromised Patients & Medical Emergencies", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "45", sNo: 45, title: "Minor Oral Surgical Procedures and Orthognathic Surgery", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "46", sNo: 46, title: "Implantology and Miscellaneous", link: "#", subject: "Oral & Maxillofacial Surgery" },
    { id: "47", sNo: 47, title: "Introduction to Complete Dentures", link: "#", subject: "Complete Denture" },
    { id: "48", sNo: 48, title: "Diagnosis and Treatment Planning", link: "#", subject: "Complete Denture" },
    { id: "49", sNo: 49, title: "Diagnostic Impressions in CD, Mouth Preparation for CD and Objective of Impression Making", link: "#", subject: "Complete Denture" },
    { id: "50", sNo: 50, title: "Primary Impression in CD & Lab Procedures Prior to Master Impression", link: "#", subject: "Complete Denture" },
    { id: "51", sNo: 51, title: "Secondary Impression in CD & Lab Procedures Prior to Jaw Relation", link: "#", subject: "Complete Denture" },
    { id: "52", sNo: 52, title: "Maxillomandibular Relations", link: "#", subject: "Complete Denture" },
    { id: "53", sNo: 53, title: "Lab Procedures Prior to Try-In", link: "#", subject: "Complete Denture" },
    { id: "54", sNo: 54, title: "Lab Procedures Prior to Insertion & Complete Denture Insertion", link: "#", subject: "Complete Denture" },
    { id: "55", sNo: 55, title: "Relining and Rebasing in Complete Dentures", link: "#", subject: "Complete Denture" },
    { id: "56", sNo: 56, title: "Special Complete Dentures and Miscellaneous", link: "#", subject: "Complete Denture" },
    { id: "57", sNo: 57, title: "Introduction to Fixed Partial Dentures", link: "#", subject: "Fixed Partial Denture" },
    { id: "58", sNo: 58, title: "Parts and Design of Fixed Partial Dentures", link: "#", subject: "Fixed Partial Denture" },
    { id: "59", sNo: 59, title: "Occlusion in Fixed Partial Dentures", link: "#", subject: "Fixed Partial Denture" },
    { id: "60", sNo: 60, title: "Types of Abutments", link: "#", subject: "Fixed Partial Denture" },
    { id: "61", sNo: 61, title: "Tooth Preparation", link: "#", subject: "Fixed Partial Denture" },
    { id: "62", sNo: 62, title: "Types of FPD", link: "#", subject: "Fixed Partial Denture" },
    { id: "63", sNo: 63, title: "Impression Making in FPD", link: "#", subject: "Fixed Partial Denture" },
    { id: "64", sNo: 64, title: "Temporization or Provisional Restorations & Lab Procedures", link: "#", subject: "Fixed Partial Denture" },
    { id: "65", sNo: 65, title: "Cementation of FPD and Miscellaneous", link: "#", subject: "Fixed Partial Denture" },
    { id: "66", sNo: 66, title: "Maxillofacial Prosthetics and Implant Dentistry", link: "#", subject: "Fixed Partial Denture" },
    { id: "67", sNo: 67, title: "Introduction, Treatment Planning and Mouth Preparation", link: "#", subject: "Removable Partial Denture" },
    { id: "68", sNo: 68, title: "Diagnosis Planning and Mouth Preparation", link: "#", subject: "Removable Partial Denture" },
    { id: "69", sNo: 69, title: "Major and Minor Connectors", link: "#", subject: "Removable Partial Denture" },
    { id: "70", sNo: 70, title: "Rests and Rest Seats", link: "#", subject: "Removable Partial Denture" },
    { id: "71", sNo: 71, title: "Direct and Indirect Retainers", link: "#", subject: "Removable Partial Denture" },
    { id: "72", sNo: 72, title: "Denture Base Considerations", link: "#", subject: "Removable Partial Denture" },
    { id: "73", sNo: 73, title: "Principles of RPD Design", link: "#", subject: "Removable Partial Denture" },
    { id: "74", sNo: 74, title: "Surveying and Mouth Preparation for RPD", link: "#", subject: "Removable Partial Denture" },
    { id: "75", sNo: 75, title: "Impression Materials and Procedures for RPD", link: "#", subject: "Removable Partial Denture" },
    { id: "76", sNo: 76, title: "Support for Distal Extension Base, Occlusal Relationship & Lab Work Authorization", link: "#", subject: "Removable Partial Denture" },
    { id: "77", sNo: 77, title: "Correction, Repairs, Additions, Relining & Rebasing of RPD & Miscellaneous", link: "#", subject: "Removable Partial Denture" },
    { id: "78", sNo: 78, title: "Introduction to Operative Dentistry", link: "#", subject: "Conservative Dentistry" },
    { id: "79", sNo: 79, title: "Preliminary Considerations for Operative Dentistry", link: "#", subject: "Conservative Dentistry" },
    { id: "80", sNo: 80, title: "Cariology", link: "#", subject: "Conservative Dentistry" },
    { id: "81", sNo: 81, title: "Instruments and Separation", link: "#", subject: "Conservative Dentistry" },
    { id: "82", sNo: 82, title: "Fundamentals in Tooth Preparation", link: "#", subject: "Conservative Dentistry" },
    { id: "83", sNo: 83, title: "Basic Concepts in Aesthetic Dentistry and Adhesion to Tooth Structure", link: "#", subject: "Conservative Dentistry" },
    { id: "84", sNo: 84, title: "Composite Resin Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "85", sNo: 85, title: "Glass Ionomer Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "86", sNo: 86, title: "Dental Ceramic Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "87", sNo: 87, title: "Amalgam Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "88", sNo: 88, title: "Pin-Retained Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "89", sNo: 89, title: "Cast Metal Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "90", sNo: 90, title: "Dental Casting Procedures", link: "#", subject: "Conservative Dentistry" },
    { id: "91", sNo: 91, title: "Direct Filling Gold Restorations", link: "#", subject: "Conservative Dentistry" },
    { id: "92", sNo: 92, title: "Lasers in Operative Dentistry", link: "#", subject: "Conservative Dentistry" },
    { id: "93", sNo: 93, title: "Miscellaneous", link: "#", subject: "Conservative Dentistry" },
    { id: "94", sNo: 94, title: "Clinical Diagnostic Aids in Endodontics", link: "#", subject: "Endodontics" },
    { id: "95", sNo: 95, title: "Endodontic Emergencies", link: "#", subject: "Endodontics" },
    { id: "96", sNo: 96, title: "Dental Pulp and Periradicular Tissues: Embryology and Anatomy", link: "#", subject: "Endodontics" },
    { id: "97", sNo: 97, title: "Diseases of Dental Pulp and Periradicular Tissues", link: "#", subject: "Endodontics" },
    { id: "98", sNo: 98, title: "Principles and Rationale of Endodontic Treatment", link: "#", subject: "Endodontics" },
    { id: "99", sNo: 99, title: "Endodontic Instruments and Sterilization", link: "#", subject: "Endodontics" },
    { id: "100", sNo: 100, title: "Endodontic Microbiology", link: "#", subject: "Endodontics" },
    { id: "101", sNo: 101, title: "Tooth Morphology and Access Cavities", link: "#", subject: "Endodontics" },
    { id: "102", sNo: 102, title: "Endodontic and Biomechanical Preparation & Working Length Determination", link: "#", subject: "Endodontics" },
    { id: "103", sNo: 103, title: "Materials in Endodontics", link: "#", subject: "Endodontics" },
    { id: "104", sNo: 104, title: "Obturation of Root Canal", link: "#", subject: "Endodontics" },
    { id: "105", sNo: 105, title: "Postendodontic Restorations", link: "#", subject: "Endodontics" },
    { id: "106", sNo: 106, title: "Mishaps and Failures in Endodontics", link: "#", subject: "Endodontics" },
    { id: "107", sNo: 107, title: "Treatments of Traumatized Teeth", link: "#", subject: "Endodontics" },
    { id: "108", sNo: 108, title: "Endodontic Surgery and Replantation & Transplantation", link: "#", subject: "Endodontics" },
    { id: "109", sNo: 109, title: "Endodontic Periodontal Interrelationships", link: "#", subject: "Endodontics" },
    { id: "110", sNo: 110, title: "Lasers and Endodontic Implants", link: "#", subject: "Endodontics" },
    { id: "111", sNo: 111, title: "Single-Visit Endodontics", link: "#", subject: "Endodontics" },
    { id: "112", sNo: 112, title: "Bleaching of Discoloured Tooth", link: "#", subject: "Endodontics" },
    { id: "113", sNo: 113, title: "Introduction to Paedodontics", link: "#", subject: "Paedodontics" },
    { id: "114", sNo: 114, title: "Examination, Diagnosis and Radiographic Techniques", link: "#", subject: "Paedodontics" },
    { id: "115", sNo: 115, title: "Theories of Child Development", link: "#", subject: "Paedodontics" },
    { id: "116", sNo: 116, title: "Parent Counselling and Child Behaviour", link: "#", subject: "Paedodontics" },
    { id: "117", sNo: 117, title: "Behavioural Science and Psychologic Management", link: "#", subject: "Paedodontics" },
    { id: "118", sNo: 118, title: "Therapeutic Management", link: "#", subject: "Paedodontics" },
    { id: "119", sNo: 119, title: "Management of Handicapped Children", link: "#", subject: "Paedodontics" },
    { id: "120", sNo: 120, title: "Management of Children with Systemic Diseases and HIV Infection", link: "#", subject: "Paedodontics" },
    { id: "121", sNo: 121, title: "Management of Children with Cleft Lip and Palate", link: "#", subject: "Paedodontics" },
    { id: "122", sNo: 122, title: "Growth and Development of the Face and Dental Arches", link: "#", subject: "Paedodontics" },
    { id: "123", sNo: 123, title: "Development and Morphology of Primary Teeth and Occlusion", link: "#", subject: "Paedodontics" },
    { id: "124", sNo: 124, title: "Acquired and Developmental Disturbances of Teeth & Oral Structures", link: "#", subject: "Paedodontics" },
    { id: "125", sNo: 125, title: "Developing Malocclusion and Preventive Measures", link: "#", subject: "Paedodontics" },
    { id: "126", sNo: 126, title: "Oral Habits", link: "#", subject: "Paedodontics" },
    { id: "127", sNo: 127, title: "Gingival and Periodontal Diseases in Children", link: "#", subject: "Paedodontics" },
    { id: "128", sNo: 128, title: "Home Oral Hygiene for Children and Adolescents", link: "#", subject: "Paedodontics" },
    { id: "129", sNo: 129, title: "Dental Caries in Children and Adolescents", link: "#", subject: "Paedodontics" },
    { id: "130", sNo: 130, title: "Pit and Fissure Sealants", link: "#", subject: "Paedodontics" },
    { id: "131", sNo: 131, title: "Atraumatic Restorative Treatment", link: "#", subject: "Paedodontics" },
    { id: "132", sNo: 132, title: "Fluorides and Oral Habits", link: "#", subject: "Paedodontics" },
    { id: "133", sNo: 133, title: "Paediatric Restorative Materials and Rubber Dam Application", link: "#", subject: "Paedodontics" },
    { id: "134", sNo: 134, title: "Restoration of Primary Carious Teeth", link: "#", subject: "Paedodontics" },
    { id: "135", sNo: 135, title: "Paediatric Endodontics", link: "#", subject: "Paedodontics" },
    { id: "136", sNo: 136, title: "Traumatic Injuries of Anterior Teeth and Management", link: "#", subject: "Paedodontics", default10m: true, default5m: true, default2m: true },
    { id: "137", sNo: 137, title: "Local Anaesthesia and Oral Surgery for the Child Patient", link: "#", subject: "Paedodontics" },
    { id: "138", sNo: 138, title: "NSAIDs, Antimicrobial Drugs and Miscellaneous", link: "#", subject: "Paedodontics" },
    { id: "139", sNo: 139, title: "Introduction to Orthodontics", link: "#", subject: "Orthodontics", default10m: true, default5m: true, default2m: true },
    { id: "140", sNo: 140, title: "General Principles and Concepts of Growth", link: "#", subject: "Orthodontics" },
    { id: "141", sNo: 141, title: "Growth and Development of Cranial and Facial Structures", link: "#", subject: "Orthodontics" },
    { id: "142", sNo: 142, title: "Development of Dentition and Occlusion", link: "#", subject: "Orthodontics" },
    { id: "143", sNo: 143, title: "Functional Development", link: "#", subject: "Orthodontics" },
    { id: "144", sNo: 144, title: "Occlusion: Basic Concepts", link: "#", subject: "Orthodontics" },
    { id: "145", sNo: 145, title: "Classification of Malocclusion", link: "#", subject: "Orthodontics" },
    { id: "146", sNo: 146, title: "Aetiology of Malocclusion", link: "#", subject: "Orthodontics" },
    { id: "147", sNo: 147, title: "Oral Habits", link: "#", subject: "Orthodontics", default10m: true, default5m: true, default2m: true },
    { id: "148", sNo: 148, title: "Orthodontic Diagnosis", link: "#", subject: "Orthodontics" },
    { id: "149", sNo: 149, title: "Cephalometrics", link: "#", subject: "Orthodontics" },
    { id: "150", sNo: 150, title: "Skeletal Maturity Indicators", link: "#", subject: "Orthodontics" },
    { id: "151", sNo: 151, title: "Model Analysis", link: "#", subject: "Orthodontics" },
    { id: "152", sNo: 152, title: "Biology and Mechanics of Tooth Movement", link: "#", subject: "Orthodontics" },
    { id: "153", sNo: 153, title: "Anchorage", link: "#", subject: "Orthodontics" },
    { id: "154", sNo: 154, title: "Age Factors in Orthodontics", link: "#", subject: "Orthodontics" },
    { id: "155", sNo: 155, title: "Preventive Orthodontics", link: "#", subject: "Orthodontics" },
    { id: "156", sNo: 156, title: "Interceptive Orthodontics", link: "#", subject: "Orthodontics" },
    { id: "157", sNo: 157, title: "Methods of Space Gaining", link: "#", subject: "Orthodontics" },
    { id: "158", sNo: 158, title: "Arch Expansion", link: "#", subject: "Orthodontics" },
    { id: "159", sNo: 159, title: "Extractions", link: "#", subject: "Orthodontics" },
    { id: "160", sNo: 160, title: "Orthodontic Appliances: General Principles", link: "#", subject: "Orthodontics" },
    { id: "161", sNo: 161, title: "Removable Orthodontic Appliances", link: "#", subject: "Orthodontics" },
    { id: "162", sNo: 162, title: "Fixed Orthodontic Appliances", link: "#", subject: "Orthodontics" },
    { id: "163", sNo: 163, title: "Myofunctional and Orthopaedic Appliances", link: "#", subject: "Orthodontics" },
    { id: "164", sNo: 164, title: "Management of Common Malocclusions", link: "#", subject: "Orthodontics" },
    { id: "165", sNo: 165, title: "Management of Class II Malocclusion", link: "#", subject: "Orthodontics" },
    { id: "166", sNo: 166, title: "Management of Class III Malocclusion", link: "#", subject: "Orthodontics" },
    { id: "167", sNo: 167, title: "Management of Open Bite, Crossbite and Deep Bite", link: "#", subject: "Orthodontics" },
    { id: "168", sNo: 168, title: "Cleft Lip and Palate", link: "#", subject: "Orthodontics" },
    { id: "169", sNo: 169, title: "Surgical Orthodontics", link: "#", subject: "Orthodontics" },
    { id: "170", sNo: 170, title: "Retention and Relapse", link: "#", subject: "Orthodontics" },
    { id: "171", sNo: 171, title: "Genetics in Orthodontics", link: "#", subject: "Orthodontics" },
    { id: "172", sNo: 172, title: "Lab Procedures", link: "#", subject: "Orthodontics" },
    { id: "173", sNo: 173, title: "Materials Used in Orthodontics", link: "#", subject: "Orthodontics" },
    { id: "174", sNo: 174, title: "Introduction", link: "#", subject: "Community Dentistry" },
    { id: "175", sNo: 175, title: "Public Health", link: "#", subject: "Community Dentistry" },
    { id: "176", sNo: 176, title: "Epidemiology", link: "#", subject: "Community Dentistry" },
    { id: "177", sNo: 177, title: "Dental Public Health", link: "#", subject: "Community Dentistry" },
    { id: "178", sNo: 178, title: "Preventive Dentistry", link: "#", subject: "Community Dentistry" },
    { id: "179", sNo: 179, title: "Fluorides", link: "#", subject: "Community Dentistry" },
    { id: "180", sNo: 180, title: "Indices Used in Preventive Dentistry", link: "#", subject: "Community Dentistry" },
    { id: "181", sNo: 181, title: "Health Statistics", link: "#", subject: "Community Dentistry" },
    { id: "182", sNo: 182, title: "Social Sciences", link: "#", subject: "Community Dentistry" },
    { id: "183", sNo: 183, title: "Gingiva", link: "#", subject: "Periodontics" },
    { id: "184", sNo: 184, title: "Tooth-Supporting Structures (PDL, Alveolar Bone, Cementum)", link: "#", subject: "Periodontics" },
    { id: "185", sNo: 185, title: "Age-Related Changes in the Periodontium", link: "#", subject: "Periodontics" },
    { id: "186", sNo: 186, title: "Classification of Periodontal Diseases", link: "#", subject: "Periodontics" },
    { id: "187", sNo: 187, title: "Epidemiology of Gingival and Periodontal Diseases", link: "#", subject: "Periodontics" },
    { id: "188", sNo: 188, title: "Periodontal Microbiology", link: "#", subject: "Periodontics" },
    { id: "189", sNo: 189, title: "Dental Calculus, Iatrogenic and Local Predisposing Factors", link: "#", subject: "Periodontics" },
    { id: "190", sNo: 190, title: "Smoking and Periodontium", link: "#", subject: "Periodontics" },
    { id: "191", sNo: 191, title: "Host Response: Basic Concepts", link: "#", subject: "Periodontics" },
    { id: "192", sNo: 192, title: "Host–Microbial Interactions in Periodontal Diseases", link: "#", subject: "Periodontics" },
    { id: "193", sNo: 193, title: "Trauma from Occlusion", link: "#", subject: "Periodontics" },
    { id: "194", sNo: 194, title: "Systemic Diseases and Periodontal Medicine", link: "#", subject: "Periodontics" },
    { id: "195", sNo: 195, title: "Dental Implants", link: "#", subject: "Periodontics" },
    { id: "196", sNo: 196, title: "Defence Mechanisms of the Gingiva", link: "#", subject: "Periodontics" },
    { id: "197", sNo: 197, title: "Gingival Inflammation and Clinical Features of Gingivitis", link: "#", subject: "Periodontics" },
    { id: "198", sNo: 198, title: "Gingival Enlargements", link: "#", subject: "Periodontics" },
    { id: "199", sNo: 199, title: "Acute Gingival Infections", link: "#", subject: "Periodontics" },
    { id: "200", sNo: 200, title: "Desquamative Gingivitis", link: "#", subject: "Periodontics" },
    { id: "201", sNo: 201, title: "Gingival and Periodontal Diseases in Children and Young Adolescents", link: "#", subject: "Periodontics" },
    { id: "202", sNo: 202, title: "Periodontal Pocket", link: "#", subject: "Periodontics" },
    { id: "203", sNo: 203, title: "Bone Loss in Periodontal Diseases", link: "#", subject: "Periodontics", default10m: true, default5m: true, default2m: true },
    { id: "204", sNo: 204, title: "Periodontitis: Chronic, Refractory & Necrotizing Ulcerative", link: "#", subject: "Periodontics" },
    { id: "205", sNo: 205, title: "Aggressive Periodontitis", link: "#", subject: "Periodontics" },
    { id: "206", sNo: 206, title: "Periodontal Abscess", link: "#", subject: "Periodontics" },
    { id: "207", sNo: 207, title: "Halitosis", link: "#", subject: "Periodontics" },
    { id: "208", sNo: 208, title: "Clinical Diagnosis & Advanced Diagnostic Methods", link: "#", subject: "Periodontics" },
    { id: "209", sNo: 209, title: "Determination of Prognosis", link: "#", subject: "Periodontics" },
    { id: "210", sNo: 210, title: "Periodontal Treatment Plan", link: "#", subject: "Periodontics" },
    { id: "211", sNo: 211, title: "Periodontal Instrumentation", link: "#", subject: "Periodontics" },
    { id: "212", sNo: 212, title: "Principles of Periodontal Instrumentation", link: "#", subject: "Periodontics" },
    { id: "213", sNo: 213, title: "Sonic and Ultrasonic Instrumentation", link: "#", subject: "Periodontics" },
    { id: "214", sNo: 214, title: "General Principles and Concepts of Growth", link: "#", subject: "Periodontics" },
    { id: "215", sNo: 215, title: "Plaque Control", link: "#", subject: "Periodontics" },
    { id: "216", sNo: 216, title: "Chemotherapeutic Agents", link: "#", subject: "Periodontics" },
    { id: "217", sNo: 217, title: "Periodontal Splints", link: "#", subject: "Periodontics" },
    { id: "218", sNo: 218, title: "General Principles of Periodontal Surgery", link: "#", subject: "Periodontics" },
    { id: "219", sNo: 219, title: "Gingival Surgical Procedures", link: "#", subject: "Periodontics" },
    { id: "220", sNo: 220, title: "Periodontal Flap Surgery", link: "#", subject: "Periodontics" },
    { id: "221", sNo: 221, title: "Resective Osseous Surgery", link: "#", subject: "Periodontics" },
    { id: "222", sNo: 222, title: "Regenerative Osseous Surgery", link: "#", subject: "Periodontics" },
    { id: "223", sNo: 223, title: "Furcation Involvement and Management", link: "#", subject: "Periodontics" },
    { id: "224", sNo: 224, title: "Endodontic Periodontal Lesions and Their Management", link: "#", subject: "Periodontics" },
    { id: "225", sNo: 225, title: "Orthodontic Periodontal Inter-Relationship", link: "#", subject: "Periodontics" },
    { id: "226", sNo: 226, title: "Perioprosthodontics / Occlusal Evaluation", link: "#", subject: "Periodontics" },
    { id: "227", sNo: 227, title: "Supportive Periodontal Treatment (Maintenance Phase)", link: "#", subject: "Periodontics" }
];